# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `devise-i18n` gem.
# Please instead update this file by running `bin/tapioca gem devise-i18n`.


# source://devise-i18n//lib/devise-i18n/view_helpers.rb#1
module DeviseI18n
  class << self
    # source://railties/8.0.0.rc1/lib/rails/engine.rb#413
    def railtie_helpers_paths; end

    # source://railties/8.0.0.rc1/lib/rails/engine.rb#396
    def railtie_namespace; end

    # source://railties/8.0.0.rc1/lib/rails/engine.rb#417
    def railtie_routes_url_helpers(include_path_helpers = T.unsafe(nil)); end

    # source://railties/8.0.0.rc1/lib/rails/engine.rb#402
    def table_name_prefix; end

    # source://railties/8.0.0.rc1/lib/rails/engine.rb#409
    def use_relative_model_naming?; end
  end
end

# source://devise-i18n//lib/devise-i18n/railtie.rb#5
class DeviseI18n::Engine < ::Rails::Engine
  class << self
    # source://activesupport/8.0.0.rc1/lib/active_support/class_attribute.rb#12
    def __callbacks; end

    # source://activesupport/8.0.0.rc1/lib/active_support/class_attribute.rb#15
    def __callbacks=(new_value); end
  end
end

# source://devise-i18n//lib/devise-i18n/railtie.rb#14
class DeviseI18n::Railtie < ::Rails::Railtie
  class << self
    # source://devise-i18n//lib/devise-i18n/railtie.rb#25
    def add(pattern); end

    # source://devise-i18n//lib/devise-i18n/railtie.rb#30
    def pattern_from(args); end
  end
end

# source://devise-i18n//lib/devise-i18n/view_helpers.rb#2
module DeviseI18n::ViewHelpers
  # Custom logic to fix case for different strings and languages.
  #
  # source://devise-i18n//lib/devise-i18n/view_helpers.rb#4
  def devise_i18n_fix_model_name_case(text, i18n_key:); end
end
