# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `phlex-rails` gem.
# Please instead update this file by running `bin/tapioca gem phlex-rails`.


# source://phlex-rails//lib/phlex/rails.rb#5
module Phlex
  class << self
    # source://phlex/2.1.2/lib/phlex.rb#31
    def __expand_attribute_cache__(file_path); end

    # source://phlex/2.1.2/lib/phlex.rb#38
    def eager_load; end

    # source://phlex/2.1.2/lib/phlex.rb#50
    def html(&block); end

    # source://phlex/2.1.2/lib/phlex.rb#66
    def svg(&block); end
  end
end

class Phlex::CSV
  include ::Phlex::Rails::CSV
  extend ::Phlex::Rails::HelperMacros

  # source://phlex/2.1.2/lib/phlex/csv.rb#12
  def initialize(collection); end

  # source://phlex/2.1.2/lib/phlex/csv.rb#116
  def around_row(item); end

  # source://phlex/2.1.2/lib/phlex/csv.rb#20
  def call(buffer = T.unsafe(nil), context: T.unsafe(nil), delimiter: T.unsafe(nil)); end

  # source://phlex/2.1.2/lib/phlex/csv.rb#18
  def collection; end

  # source://phlex/2.1.2/lib/phlex/csv.rb#124
  def content_type; end

  # source://phlex/2.1.2/lib/phlex/csv.rb#128
  def delimiter; end

  # source://phlex-rails//lib/phlex/rails/csv.rb#6
  def each_item(&_arg0); end

  # source://phlex/2.1.2/lib/phlex/csv.rb#120
  def filename; end

  private

  # source://phlex/2.1.2/lib/phlex/csv.rb#157
  def __escape__(buffer, value, escape_csv_injection:, strip_whitespace:, escape_regex:); end

  # source://phlex/2.1.2/lib/phlex/csv.rb#134
  def column(header = T.unsafe(nil), value); end

  # source://phlex/2.1.2/lib/phlex/csv.rb#226
  def ensure_escape_csv_injection_configured!; end

  # source://phlex/2.1.2/lib/phlex/csv.rb#153
  def escape_csv_injection?; end

  # source://phlex/2.1.2/lib/phlex/csv.rb#216
  def method_missing(method_name, *_arg1, **_arg2, &_arg3); end

  # source://phlex/2.1.2/lib/phlex/csv.rb#143
  def render_headers?; end

  # source://phlex/2.1.2/lib/phlex/csv.rb#211
  def respond_to_missing?(method_name, include_private); end

  # source://phlex/2.1.2/lib/phlex/csv.rb#148
  def trim_whitespace?; end
end

class Phlex::HTML < ::Phlex::SGML
  include ::Phlex::Rails::HTML
  include ::Phlex::Rails::SGML
  extend ::Phlex::Rails::SGML::ClassMethods
  extend ::Phlex::Rails::HelperMacros
end

# source://phlex-rails//lib/phlex/rails.rb#6
module Phlex::Rails; end

# source://phlex-rails//lib/phlex/rails/buffered.rb#4
class Phlex::Rails::Buffered < ::BasicObject
  # @return [Buffered] a new instance of Buffered
  #
  # source://phlex-rails//lib/phlex/rails/buffered.rb#5
  def initialize(object, component:); end

  # source://phlex-rails//lib/phlex/rails/buffered.rb#14
  def method_missing(*_arg0, **_arg1, &block); end

  private

  # @return [Boolean]
  #
  # source://phlex-rails//lib/phlex/rails/buffered.rb#10
  def respond_to_missing?(*_arg0, **_arg1, &_arg2); end
end

# source://phlex-rails//lib/phlex/rails/csv.rb#5
module Phlex::Rails::CSV
  # source://phlex-rails//lib/phlex/rails/csv.rb#6
  def each_item(&_arg0); end
end

# source://phlex-rails//lib/phlex/rails/checkbox_builder.rb#3
class Phlex::Rails::CheckboxBuilder < ::Phlex::Rails::Decorator
  # source://phlex-rails//lib/phlex/rails/decorator.rb#6
  def checkbox(*_arg0, **_arg1, &_arg2); end

  # source://phlex-rails//lib/phlex/rails/decorator.rb#6
  def label(*_arg0, **_arg1, &_arg2); end

  # source://phlex-rails//lib/phlex/rails/checkbox_builder.rb#6
  def object(*_arg0, **_arg1, &_arg2); end

  # source://phlex-rails//lib/phlex/rails/checkbox_builder.rb#4
  def text(*_arg0, **_arg1, &_arg2); end

  # source://phlex-rails//lib/phlex/rails/checkbox_builder.rb#5
  def value(*_arg0, **_arg1, &_arg2); end
end

# source://phlex-rails//lib/phlex/rails/decorator.rb#3
class Phlex::Rails::Decorator < ::BasicObject
  # @return [Decorator] a new instance of Decorator
  #
  # source://phlex-rails//lib/phlex/rails/decorator.rb#14
  def initialize(object, component:); end

  # source://phlex-rails//lib/phlex/rails/decorator.rb#23
  def method_missing(*_arg0, **_arg1, &_arg2); end

  private

  # @return [Boolean]
  #
  # source://phlex-rails//lib/phlex/rails/decorator.rb#19
  def respond_to_missing?(method_name, include_private = T.unsafe(nil)); end

  class << self
    # source://phlex-rails//lib/phlex/rails/decorator.rb#4
    def output(method_name); end
  end
end

# source://phlex-rails//lib/phlex/rails/form_builder.rb#3
class Phlex::Rails::FormBuilder < ::Phlex::Rails::Decorator
  def __caller_locations__(*_arg0); end

  # source://phlex-rails//lib/phlex/rails/decorator.rb#6
  def button(*_arg0, **_arg1, &_arg2); end

  # source://phlex-rails//lib/phlex/rails/decorator.rb#6
  def check_box(*_arg0, **_arg1, &_arg2); end

  # source://phlex-rails//lib/phlex/rails/decorator.rb#6
  def checkbox(*_arg0, **_arg1, &_arg2); end

  # source://phlex-rails//lib/phlex/rails/form_builder.rb#52
  def collection_check_boxes(*_arg0, **_arg1, &block); end

  # source://phlex-rails//lib/phlex/rails/form_builder.rb#64
  def collection_checkboxes(*_arg0, **_arg1, &block); end

  # source://phlex-rails//lib/phlex/rails/form_builder.rb#76
  def collection_radio_buttons(*_arg0, **_arg1, &block); end

  # source://phlex-rails//lib/phlex/rails/decorator.rb#6
  def collection_select(*_arg0, **_arg1, &_arg2); end

  # source://phlex-rails//lib/phlex/rails/decorator.rb#6
  def color_field(*_arg0, **_arg1, &_arg2); end

  # source://phlex-rails//lib/phlex/rails/decorator.rb#6
  def date_field(*_arg0, **_arg1, &_arg2); end

  # source://phlex-rails//lib/phlex/rails/decorator.rb#6
  def date_select(*_arg0, **_arg1, &_arg2); end

  # source://phlex-rails//lib/phlex/rails/decorator.rb#6
  def datetime_field(*_arg0, **_arg1, &_arg2); end

  # source://phlex-rails//lib/phlex/rails/decorator.rb#6
  def datetime_local_field(*_arg0, **_arg1, &_arg2); end

  # source://phlex-rails//lib/phlex/rails/decorator.rb#6
  def datetime_select(*_arg0, **_arg1, &_arg2); end

  # source://phlex-rails//lib/phlex/rails/decorator.rb#6
  def email_field(*_arg0, **_arg1, &_arg2); end

  # source://phlex-rails//lib/phlex/rails/form_builder.rb#8
  def field_id(*_arg0, **_arg1, &_arg2); end

  # source://phlex-rails//lib/phlex/rails/form_builder.rb#9
  def field_name(*_arg0, **_arg1, &_arg2); end

  # source://phlex-rails//lib/phlex/rails/form_builder.rb#88
  def fields(*_arg0, **_arg1, &block); end

  # source://phlex-rails//lib/phlex/rails/form_builder.rb#100
  def fields_for(*_arg0, **_arg1, &block); end

  # source://phlex-rails//lib/phlex/rails/decorator.rb#6
  def file_field(*_arg0, **_arg1, &_arg2); end

  # source://phlex-rails//lib/phlex/rails/decorator.rb#6
  def grouped_collection_select(*_arg0, **_arg1, &_arg2); end

  # source://phlex-rails//lib/phlex/rails/decorator.rb#6
  def hidden_field(*_arg0, **_arg1, &_arg2); end

  # source://phlex-rails//lib/phlex/rails/form_builder.rb#6
  def id(*_arg0, **_arg1, &_arg2); end

  # source://phlex-rails//lib/phlex/rails/form_builder.rb#112
  def label(*_arg0, **_arg1, &block); end

  # source://phlex-rails//lib/phlex/rails/decorator.rb#6
  def month_field(*_arg0, **_arg1, &_arg2); end

  # source://phlex-rails//lib/phlex/rails/form_builder.rb#12
  def multipart=(value); end

  # source://phlex-rails//lib/phlex/rails/decorator.rb#6
  def number_field(*_arg0, **_arg1, &_arg2); end

  # source://phlex-rails//lib/phlex/rails/decorator.rb#6
  def password_field(*_arg0, **_arg1, &_arg2); end

  # source://phlex-rails//lib/phlex/rails/decorator.rb#6
  def phone_field(*_arg0, **_arg1, &_arg2); end

  # source://phlex-rails//lib/phlex/rails/decorator.rb#6
  def radio_button(*_arg0, **_arg1, &_arg2); end

  # source://phlex-rails//lib/phlex/rails/decorator.rb#6
  def range_field(*_arg0, **_arg1, &_arg2); end

  # source://phlex-rails//lib/phlex/rails/decorator.rb#6
  def rich_text_area(*_arg0, **_arg1, &_arg2); end

  # source://phlex-rails//lib/phlex/rails/decorator.rb#6
  def rich_textarea(*_arg0, **_arg1, &_arg2); end

  # source://phlex-rails//lib/phlex/rails/decorator.rb#6
  def search_field(*_arg0, **_arg1, &_arg2); end

  # source://phlex-rails//lib/phlex/rails/decorator.rb#6
  def select(*_arg0, **_arg1, &_arg2); end

  # source://phlex-rails//lib/phlex/rails/decorator.rb#6
  def submit(*_arg0, **_arg1, &_arg2); end

  # source://phlex-rails//lib/phlex/rails/decorator.rb#6
  def telephone_field(*_arg0, **_arg1, &_arg2); end

  # source://phlex-rails//lib/phlex/rails/decorator.rb#6
  def text_area(*_arg0, **_arg1, &_arg2); end

  # source://phlex-rails//lib/phlex/rails/decorator.rb#6
  def text_field(*_arg0, **_arg1, &_arg2); end

  # source://phlex-rails//lib/phlex/rails/decorator.rb#6
  def textarea(*_arg0, **_arg1, &_arg2); end

  # source://phlex-rails//lib/phlex/rails/decorator.rb#6
  def time_field(*_arg0, **_arg1, &_arg2); end

  # source://phlex-rails//lib/phlex/rails/decorator.rb#6
  def time_select(*_arg0, **_arg1, &_arg2); end

  # source://phlex-rails//lib/phlex/rails/decorator.rb#6
  def time_zone_select(*_arg0, **_arg1, &_arg2); end

  # source://phlex-rails//lib/phlex/rails/form_builder.rb#7
  def to_model(*_arg0, **_arg1, &_arg2); end

  # source://phlex-rails//lib/phlex/rails/form_builder.rb#10
  def to_partial_path(*_arg0, **_arg1, &_arg2); end

  # source://phlex-rails//lib/phlex/rails/decorator.rb#6
  def url_field(*_arg0, **_arg1, &_arg2); end

  # source://phlex-rails//lib/phlex/rails/decorator.rb#6
  def week_field(*_arg0, **_arg1, &_arg2); end

  # source://phlex-rails//lib/phlex/rails/decorator.rb#6
  def weekday_select(*_arg0, **_arg1, &_arg2); end
end

# source://phlex-rails//lib/phlex/rails/html.rb#3
module Phlex::Rails::HTML
  include ::Phlex::Rails::SGML

  mixes_in_class_methods ::Phlex::Rails::SGML::ClassMethods
  mixes_in_class_methods ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/html.rb#9
  def format; end

  class << self
    # @private
    #
    # source://phlex-rails//lib/phlex/rails/html.rb#4
    def included(base); end
  end
end

# source://phlex-rails//lib/phlex/rails/helper_macros.rb#3
module Phlex::Rails::HelperMacros
  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#36
  def register_builder_yielding_helper(method_name, builder); end

  # Register a Rails helper that returns safe HTML to be pushed to the output buffer.
  #
  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#5
  def register_output_helper(method_name); end

  # Register a Rails helper that returns a value that shouldn’t be pushed to the output buffer.
  #
  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#22
  def register_value_helper(method_name); end
end

# An adapter for Rails routing helpers, such as <code>article_path</code>.
#
# source://phlex-rails//lib/phlex/rails/helpers.rb#3
module Phlex::Rails::Helpers; end

# source://phlex-rails//lib/phlex/rails/helpers/action_cable_meta_tag.rb#3
module Phlex::Rails::Helpers::ActionCableMetaTag
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def action_cable_meta_tag(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/action_name.rb#3
module Phlex::Rails::Helpers::ActionName
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def action_name(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/asset_path.rb#3
module Phlex::Rails::Helpers::AssetPath
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def asset_path(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/asset_url.rb#3
module Phlex::Rails::Helpers::AssetURL
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def asset_url(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/audio_path.rb#3
module Phlex::Rails::Helpers::AudioPath
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def audio_path(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/audio_tag.rb#3
module Phlex::Rails::Helpers::AudioTag
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def audio_tag(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/audio_url.rb#3
module Phlex::Rails::Helpers::AudioURL
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def audio_url(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/auto_discovery_link_tag.rb#3
module Phlex::Rails::Helpers::AutoDiscoveryLinkTag
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def auto_discovery_link_tag(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/build_tag_values.rb#3
module Phlex::Rails::Helpers::BuildTagValues
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def build_tag_values(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/button_tag.rb#3
module Phlex::Rails::Helpers::ButtonTag
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def button_tag(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/button_to.rb#3
module Phlex::Rails::Helpers::ButtonTo
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def button_to(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/csp_meta_tag.rb#3
module Phlex::Rails::Helpers::CSPMetaTag
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def csp_meta_tag(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/csrf_meta_tags.rb#3
module Phlex::Rails::Helpers::CSRFMetaTags
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def csrf_meta_tags(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/check_box.rb#3
module Phlex::Rails::Helpers::CheckBox
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def check_box(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/check_box_tag.rb#3
module Phlex::Rails::Helpers::CheckBoxTag
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def check_box_tag(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/class_names.rb#3
module Phlex::Rails::Helpers::ClassNames
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def class_names(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/collection_check_boxes.rb#3
module Phlex::Rails::Helpers::CollectionCheckBoxes
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#40
  def collection_check_boxes(*args, **kwargs); end
end

# source://phlex-rails//lib/phlex/rails/helpers/collection_radio_buttons.rb#3
module Phlex::Rails::Helpers::CollectionRadioButtons
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#40
  def collection_radio_buttons(*args, **kwargs); end
end

# source://phlex-rails//lib/phlex/rails/helpers/collection_select.rb#3
module Phlex::Rails::Helpers::CollectionSelect
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def collection_select(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/color_field.rb#3
module Phlex::Rails::Helpers::ColorField
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def color_field(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/color_field_tag.rb#3
module Phlex::Rails::Helpers::ColorFieldTag
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def color_field_tag(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/compute_asset_extname.rb#3
module Phlex::Rails::Helpers::ComputeAssetExtname
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def compute_asset_extname(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/compute_asset_host.rb#3
module Phlex::Rails::Helpers::ComputeAssetHost
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def compute_asset_host(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/compute_asset_path.rb#3
module Phlex::Rails::Helpers::ComputeAssetPath
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def compute_asset_path(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/content_for.rb#3
module Phlex::Rails::Helpers::ContentFor
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def content_for(*args, **kwargs, &block); end

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def content_for?(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/content_tag.rb#3
module Phlex::Rails::Helpers::ContentTag
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def content_tag(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/controller_name.rb#3
module Phlex::Rails::Helpers::ControllerName
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def controller_name(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/controller_path.rb#3
module Phlex::Rails::Helpers::ControllerPath
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def controller_path(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/current_cycle.rb#3
module Phlex::Rails::Helpers::CurrentCycle
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def current_cycle(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/current_page.rb#3
module Phlex::Rails::Helpers::CurrentPage
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def current_page?(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/cycle.rb#3
module Phlex::Rails::Helpers::Cycle
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def cycle(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/dom_class.rb#3
module Phlex::Rails::Helpers::DOMClass
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def dom_class(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/dom_id.rb#3
module Phlex::Rails::Helpers::DOMID
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def dom_id(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/date_field.rb#3
module Phlex::Rails::Helpers::DateField
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def date_field(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/date_field_tag.rb#3
module Phlex::Rails::Helpers::DateFieldTag
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def date_field_tag(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/date_select.rb#3
module Phlex::Rails::Helpers::DateSelect
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def date_select(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/datetime_field.rb#3
module Phlex::Rails::Helpers::DatetimeField
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def datetime_field(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/datetime_field_tag.rb#3
module Phlex::Rails::Helpers::DatetimeFieldTag
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def datetime_field_tag(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/datetime_local_field.rb#3
module Phlex::Rails::Helpers::DatetimeLocalField
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def datetime_local_field(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/datetime_local_field_tag.rb#3
module Phlex::Rails::Helpers::DatetimeLocalFieldTag
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def datetime_local_field_tag(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/datetime_select.rb#3
module Phlex::Rails::Helpers::DatetimeSelect
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def datetime_select(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/debug.rb#3
module Phlex::Rails::Helpers::Debug
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def debug(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/default_url_options.rb#3
module Phlex::Rails::Helpers::DefaultURLOptions
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def default_url_options(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/distance_of_time_in_words.rb#3
module Phlex::Rails::Helpers::DistanceOfTimeInWords
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def distance_of_time_in_words(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/distance_of_time_in_words_to_now.rb#3
module Phlex::Rails::Helpers::DistanceOfTimeInWordsToNow
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def distance_of_time_in_words_to_now(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/email_field.rb#3
module Phlex::Rails::Helpers::EmailField
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def email_field(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/email_field_tag.rb#3
module Phlex::Rails::Helpers::EmailFieldTag
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def email_field_tag(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/error_message.rb#3
module Phlex::Rails::Helpers::ErrorMessage
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def error_message(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/error_wrapping.rb#3
module Phlex::Rails::Helpers::ErrorWrapping
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def error_wrapping(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/escape_once.rb#3
module Phlex::Rails::Helpers::EscapeOnce
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def escape_once(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/excerpt.rb#3
module Phlex::Rails::Helpers::Excerpt
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def excerpt(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/favicon_link_tag.rb#3
module Phlex::Rails::Helpers::FaviconLinkTag
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def favicon_link_tag(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/field_id.rb#3
module Phlex::Rails::Helpers::FieldID
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def field_id(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/field_name.rb#3
module Phlex::Rails::Helpers::FieldName
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def field_name(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/field_set_tag.rb#3
module Phlex::Rails::Helpers::FieldSetTag
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def field_set_tag(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/fields.rb#3
module Phlex::Rails::Helpers::Fields
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#40
  def fields(*args, **kwargs); end
end

# source://phlex-rails//lib/phlex/rails/helpers/fields_for.rb#3
module Phlex::Rails::Helpers::FieldsFor
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#40
  def fields_for(*args, **kwargs); end
end

# source://phlex-rails//lib/phlex/rails/helpers/file_field.rb#3
module Phlex::Rails::Helpers::FileField
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def file_field(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/file_field_tag.rb#3
module Phlex::Rails::Helpers::FileFieldTag
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def file_field_tag(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/flash.rb#3
module Phlex::Rails::Helpers::Flash
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def flash(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/font_path.rb#3
module Phlex::Rails::Helpers::FontPath
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def font_path(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/font_url.rb#3
module Phlex::Rails::Helpers::FontURL
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def font_url(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/form_authenticity_token.rb#3
module Phlex::Rails::Helpers::FormAuthenticityToken
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def form_authenticity_token(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/form_for.rb#3
module Phlex::Rails::Helpers::FormFor
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#40
  def form_for(*args, **kwargs); end
end

# source://phlex-rails//lib/phlex/rails/helpers/form_tag.rb#3
module Phlex::Rails::Helpers::FormTag
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def form_tag(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/form_with.rb#3
module Phlex::Rails::Helpers::FormWith
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#40
  def form_with(*args, **kwargs); end
end

# source://phlex-rails//lib/phlex/rails/helpers/grouped_collection_select.rb#3
module Phlex::Rails::Helpers::GroupedCollectionSelect
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def grouped_collection_select(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/grouped_options_for_select.rb#3
module Phlex::Rails::Helpers::GroupedOptionsForSelect
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def grouped_options_for_select(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/hidden_field.rb#3
module Phlex::Rails::Helpers::HiddenField
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def hidden_field(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/hidden_field_tag.rb#3
module Phlex::Rails::Helpers::HiddenFieldTag
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def hidden_field_tag(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/highlight.rb#3
module Phlex::Rails::Helpers::Highlight
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def highlight(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/image_path.rb#3
module Phlex::Rails::Helpers::ImagePath
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def image_path(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/image_submit_tag.rb#3
module Phlex::Rails::Helpers::ImageSubmitTag
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def image_submit_tag(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/image_tag.rb#3
module Phlex::Rails::Helpers::ImageTag
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def image_tag(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/image_url.rb#3
module Phlex::Rails::Helpers::ImageURL
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def image_url(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/javascript_import_module_tag.rb#3
module Phlex::Rails::Helpers::JavascriptImportModuleTag
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def javascript_import_module_tag(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/javascript_importmap_tags.rb#3
module Phlex::Rails::Helpers::JavascriptImportmapTags
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def javascript_importmap_tags(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/javascript_include_tag.rb#3
module Phlex::Rails::Helpers::JavascriptIncludeTag
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def javascript_include_tag(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/javascript_path.rb#3
module Phlex::Rails::Helpers::JavascriptPath
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def javascript_path(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/javascript_tag.rb#3
module Phlex::Rails::Helpers::JavascriptTag
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def javascript_tag(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/javascript_url.rb#3
module Phlex::Rails::Helpers::JavascriptURL
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def javascript_url(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/l.rb#3
module Phlex::Rails::Helpers::L
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def l(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/label.rb#3
module Phlex::Rails::Helpers::Label
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#40
  def label(*args, **kwargs); end
end

# source://phlex-rails//lib/phlex/rails/helpers/label_tag.rb#3
module Phlex::Rails::Helpers::LabelTag
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def label_tag(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/link_to.rb#3
module Phlex::Rails::Helpers::LinkTo
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def link_to(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/link_to_if.rb#3
module Phlex::Rails::Helpers::LinkToIf
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def link_to_if(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/link_to_unless.rb#3
module Phlex::Rails::Helpers::LinkToUnless
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def link_to_unless(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/link_to_unless_current.rb#3
module Phlex::Rails::Helpers::LinkToUnlessCurrent
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def link_to_unless_current(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/localize.rb#3
module Phlex::Rails::Helpers::Localize
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def localize(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/mail_to.rb#3
module Phlex::Rails::Helpers::MailTo
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def mail_to(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/month_field.rb#3
module Phlex::Rails::Helpers::MonthField
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def month_field(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/month_field_tag.rb#3
module Phlex::Rails::Helpers::MonthFieldTag
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def month_field_tag(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/notice.rb#3
module Phlex::Rails::Helpers::Notice
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def notice(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/number_field.rb#3
module Phlex::Rails::Helpers::NumberField
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def number_field(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/number_field_tag.rb#3
module Phlex::Rails::Helpers::NumberFieldTag
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def number_field_tag(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/number_to_currency.rb#3
module Phlex::Rails::Helpers::NumberToCurrency
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def number_to_currency(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/number_to_human.rb#3
module Phlex::Rails::Helpers::NumberToHuman
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def number_to_human(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/number_to_human_size.rb#3
module Phlex::Rails::Helpers::NumberToHumanSize
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def number_to_human_size(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/number_to_percentage.rb#3
module Phlex::Rails::Helpers::NumberToPercentage
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def number_to_percentage(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/number_to_phone.rb#3
module Phlex::Rails::Helpers::NumberToPhone
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def number_to_phone(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/number_with_delimiter.rb#3
module Phlex::Rails::Helpers::NumberWithDelimiter
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def number_with_delimiter(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/number_with_precision.rb#3
module Phlex::Rails::Helpers::NumberWithPrecision
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def number_with_precision(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/object.rb#3
module Phlex::Rails::Helpers::Object
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def object(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/option_groups_from_collection_for_select.rb#3
module Phlex::Rails::Helpers::OptionGroupsFromCollectionForSelect
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def option_groups_from_collection_for_select(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/options_for_select.rb#3
module Phlex::Rails::Helpers::OptionsForSelect
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def options_for_select(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/options_from_collection_for_select.rb#3
module Phlex::Rails::Helpers::OptionsFromCollectionForSelect
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def options_from_collection_for_select(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/password_field.rb#3
module Phlex::Rails::Helpers::PasswordField
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def password_field(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/password_field_tag.rb#3
module Phlex::Rails::Helpers::PasswordFieldTag
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def password_field_tag(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/path_to_asset.rb#3
module Phlex::Rails::Helpers::PathToAsset
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def path_to_asset(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/path_to_audio.rb#3
module Phlex::Rails::Helpers::PathToAudio
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def path_to_audio(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/path_to_font.rb#3
module Phlex::Rails::Helpers::PathToFont
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def path_to_font(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/path_to_image.rb#3
module Phlex::Rails::Helpers::PathToImage
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def path_to_image(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/path_to_javascript.rb#3
module Phlex::Rails::Helpers::PathToJavascript
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def path_to_javascript(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/path_to_stylesheet.rb#3
module Phlex::Rails::Helpers::PathToStylesheet
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def path_to_stylesheet(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/path_to_video.rb#3
module Phlex::Rails::Helpers::PathToVideo
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def path_to_video(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/phone_field.rb#3
module Phlex::Rails::Helpers::PhoneField
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def phone_field(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/phone_field_tag.rb#3
module Phlex::Rails::Helpers::PhoneFieldTag
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def phone_field_tag(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/phone_to.rb#3
module Phlex::Rails::Helpers::PhoneTo
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def phone_to(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/pluralize.rb#3
module Phlex::Rails::Helpers::Pluralize
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def pluralize(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/preload_link_tag.rb#3
module Phlex::Rails::Helpers::PreloadLinkTag
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def preload_link_tag(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/provide.rb#3
module Phlex::Rails::Helpers::Provide
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def provide(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/public_compute_asset_path.rb#3
module Phlex::Rails::Helpers::PublicComputeAssetPath
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def public_compute_asset_path(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/radio_button.rb#3
module Phlex::Rails::Helpers::RadioButton
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def radio_button(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/radio_button_tag.rb#3
module Phlex::Rails::Helpers::RadioButtonTag
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def radio_button_tag(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/range_field.rb#3
module Phlex::Rails::Helpers::RangeField
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def range_field(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/range_field_tag.rb#3
module Phlex::Rails::Helpers::RangeFieldTag
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def range_field_tag(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/request.rb#3
module Phlex::Rails::Helpers::Request
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def request(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/reset_cycle.rb#3
module Phlex::Rails::Helpers::ResetCycle
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def reset_cycle(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/rich_text_area.rb#3
module Phlex::Rails::Helpers::RichTextArea
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def rich_text_area(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/routes.rb#5
module Phlex::Rails::Helpers::Routes
  include ::ActionDispatch::Routing::PolymorphicRoutes
  include ::ActionDispatch::Routing::UrlFor
  include ::ActionDispatch::Routing::RouteSet::MountedHelpers
  include ::Phlex::Rails::Helpers::URLOptions
  include ::Phlex::Rails::Helpers::DefaultURLOptions

  # source://actionpack/8.0.0.rc1/lib/action_dispatch/routing/url_for.rb#102
  def default_url_options=(val); end

  class << self
    # source://actionpack/8.0.0.rc1/lib/action_dispatch/routing/route_set.rb#612
    def _routes; end

    # source://actionpack/8.0.0.rc1/lib/action_dispatch/routing/url_for.rb#102
    def default_url_options=(val); end
  end
end

# source://phlex-rails//lib/phlex/rails/helpers/sms_to.rb#3
module Phlex::Rails::Helpers::SMSTo
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def sms_to(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/sanitize.rb#3
module Phlex::Rails::Helpers::Sanitize
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def sanitize(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/sanitize_css.rb#3
module Phlex::Rails::Helpers::SanitizeCSS
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def sanitize_css(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/search_field.rb#3
module Phlex::Rails::Helpers::SearchField
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def search_field(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/search_field_tag.rb#3
module Phlex::Rails::Helpers::SearchFieldTag
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def search_field_tag(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/select.rb#3
module Phlex::Rails::Helpers::Select
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def select(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/select_date.rb#3
module Phlex::Rails::Helpers::SelectDate
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def select_date(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/select_datetime.rb#3
module Phlex::Rails::Helpers::SelectDatetime
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def select_datetime(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/select_day.rb#3
module Phlex::Rails::Helpers::SelectDay
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def select_day(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/select_hour.rb#3
module Phlex::Rails::Helpers::SelectHour
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def select_hour(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/select_minute.rb#3
module Phlex::Rails::Helpers::SelectMinute
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def select_minute(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/select_month.rb#3
module Phlex::Rails::Helpers::SelectMonth
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def select_month(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/select_second.rb#3
module Phlex::Rails::Helpers::SelectSecond
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def select_second(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/select_tag.rb#3
module Phlex::Rails::Helpers::SelectTag
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def select_tag(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/select_time.rb#3
module Phlex::Rails::Helpers::SelectTime
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def select_time(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/select_year.rb#3
module Phlex::Rails::Helpers::SelectYear
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def select_year(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/simple_format.rb#3
module Phlex::Rails::Helpers::SimpleFormat
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def simple_format(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/strip_links.rb#3
module Phlex::Rails::Helpers::StripLinks
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def strip_links(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/strip_tags.rb#3
module Phlex::Rails::Helpers::StripTags
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def strip_tags(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/stylesheet_link_tag.rb#3
module Phlex::Rails::Helpers::StylesheetLinkTag
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def stylesheet_link_tag(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/stylesheet_path.rb#3
module Phlex::Rails::Helpers::StylesheetPath
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def stylesheet_path(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/stylesheet_url.rb#3
module Phlex::Rails::Helpers::StylesheetURL
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def stylesheet_url(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/submit_tag.rb#3
module Phlex::Rails::Helpers::SubmitTag
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def submit_tag(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/t.rb#3
Phlex::Rails::Helpers::T = Phlex::Rails::Helpers::Translate

# source://phlex-rails//lib/phlex/rails/helpers/tag.rb#3
module Phlex::Rails::Helpers::Tag
  # [Rails Docs](https://api.rubyonrails.org/classes/ActionView/Helpers/TagHelper.html#method-i-tag)
  #
  # source://phlex-rails//lib/phlex/rails/helpers/tag.rb#5
  def tag(*_arg0, **_arg1, &_arg2); end
end

# source://phlex-rails//lib/phlex/rails/helpers/telephone_field.rb#3
module Phlex::Rails::Helpers::TelephoneField
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def telephone_field(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/telephone_field_tag.rb#3
module Phlex::Rails::Helpers::TelephoneFieldTag
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def telephone_field_tag(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/text_area.rb#3
module Phlex::Rails::Helpers::TextArea
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def text_area(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/text_area_tag.rb#3
module Phlex::Rails::Helpers::TextAreaTag
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def text_area_tag(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/text_field.rb#3
module Phlex::Rails::Helpers::TextField
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def text_field(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/text_field_tag.rb#3
module Phlex::Rails::Helpers::TextFieldTag
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def text_field_tag(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/time_ago_in_words.rb#3
module Phlex::Rails::Helpers::TimeAgoInWords
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def time_ago_in_words(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/time_field.rb#3
module Phlex::Rails::Helpers::TimeField
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def time_field(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/time_field_tag.rb#3
module Phlex::Rails::Helpers::TimeFieldTag
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def time_field_tag(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/time_select.rb#3
module Phlex::Rails::Helpers::TimeSelect
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def time_select(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/time_tag.rb#3
module Phlex::Rails::Helpers::TimeTag
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def time_tag(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/time_zone_options_for_select.rb#3
module Phlex::Rails::Helpers::TimeZoneOptionsForSelect
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def time_zone_options_for_select(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/time_zone_select.rb#3
module Phlex::Rails::Helpers::TimeZoneSelect
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def time_zone_select(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/token_list.rb#3
module Phlex::Rails::Helpers::TokenList
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def token_list(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/translate.rb#3
module Phlex::Rails::Helpers::Translate
  mixes_in_class_methods ::Phlex::Rails::Helpers::Translate::ClassMethods

  # [Rails Docs](https://api.rubyonrails.org/classes/AbstractController/Translation.html#method-i-translate)
  # [Rails Docs](https://api.rubyonrails.org/classes/AbstractController/Translation.html#method-i-t)
  #
  # source://phlex-rails//lib/phlex/rails/helpers/translate.rb#19
  def t(key, **_arg1); end

  # [Rails Docs](https://api.rubyonrails.org/classes/AbstractController/Translation.html#method-i-translate)
  #
  # source://phlex-rails//lib/phlex/rails/helpers/translate.rb#19
  def translate(key, **_arg1); end

  class << self
    # @private
    #
    # source://phlex-rails//lib/phlex/rails/helpers/translate.rb#14
    def included(base); end
  end
end

# source://phlex-rails//lib/phlex/rails/helpers/translate.rb#4
module Phlex::Rails::Helpers::Translate::ClassMethods
  # source://phlex-rails//lib/phlex/rails/helpers/translate.rb#5
  def translation_path; end
end

# source://phlex-rails//lib/phlex/rails/helpers/truncate.rb#3
module Phlex::Rails::Helpers::Truncate
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def truncate(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/turbo_frame_tag.rb#3
module Phlex::Rails::Helpers::TurboFrameTag
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def turbo_frame_tag(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/turbo_include_tags.rb#3
module Phlex::Rails::Helpers::TurboIncludeTags
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def turbo_include_tags(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/turbo_refresh_method_tag.rb#3
module Phlex::Rails::Helpers::TurboRefreshMethodTag
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def turbo_refresh_method_tag(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/turbo_refresh_scroll_tag.rb#3
module Phlex::Rails::Helpers::TurboRefreshScrollTag
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def turbo_refresh_scroll_tag(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/turbo_refreshes_with.rb#3
module Phlex::Rails::Helpers::TurboRefreshesWith
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def turbo_refreshes_with(*args, **kwargs, &block); end
end

# An adapter for the turbo-rails <code>turbo_stream</code> helper.
#
# @see https://github.com/hotwired/turbo-rails
#
# source://phlex-rails//lib/phlex/rails/helpers/turbo_stream.rb#5
module Phlex::Rails::Helpers::TurboStream
  extend ::Phlex::Rails::HelperMacros

  # [Turbo Docs](https://rubydoc.info/github/hotwired/turbo-rails/Turbo/StreamsHelper#turbo_stream-instance_method)
  #
  # source://phlex-rails//lib/phlex/rails/helpers/turbo_stream.rb#9
  def turbo_stream(*_arg0, **_arg1, &_arg2); end
end

# source://phlex-rails//lib/phlex/rails/helpers/turbo_stream_from.rb#3
module Phlex::Rails::Helpers::TurboStreamFrom
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def turbo_stream_from(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/url_field.rb#3
module Phlex::Rails::Helpers::URLField
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def url_field(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/url_field_tag.rb#3
module Phlex::Rails::Helpers::URLFieldTag
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def url_field_tag(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/url_for.rb#3
module Phlex::Rails::Helpers::URLFor
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def url_for(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/url_options.rb#3
module Phlex::Rails::Helpers::URLOptions
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def url_options(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/url_to_asset.rb#3
module Phlex::Rails::Helpers::URLToAsset
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def url_to_asset(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/url_to_audio.rb#3
module Phlex::Rails::Helpers::URLToAudio
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def url_to_audio(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/url_to_font.rb#3
module Phlex::Rails::Helpers::URLToFont
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def url_to_font(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/url_to_image.rb#3
module Phlex::Rails::Helpers::URLToImage
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def url_to_image(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/url_to_javascript.rb#3
module Phlex::Rails::Helpers::URLToJavascript
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def url_to_javascript(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/url_to_stylesheet.rb#3
module Phlex::Rails::Helpers::URLToStylesheet
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def url_to_stylesheet(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/url_to_video.rb#3
module Phlex::Rails::Helpers::URLToVideo
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def url_to_video(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/utf8_enforcer_tag.rb#3
module Phlex::Rails::Helpers::UTF8EnforcerTag
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def utf8_enforcer_tag(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/video_path.rb#3
module Phlex::Rails::Helpers::VideoPath
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def video_path(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/video_tag.rb#3
module Phlex::Rails::Helpers::VideoTag
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def video_tag(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/video_url.rb#3
module Phlex::Rails::Helpers::VideoURL
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def video_url(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/week_field.rb#3
module Phlex::Rails::Helpers::WeekField
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def week_field(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/week_field_tag.rb#3
module Phlex::Rails::Helpers::WeekFieldTag
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def week_field_tag(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/weekday_options_for_select.rb#3
module Phlex::Rails::Helpers::WeekdayOptionsForSelect
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def weekday_options_for_select(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/weekday_select.rb#3
module Phlex::Rails::Helpers::WeekdaySelect
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def weekday_select(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/with_output_buffer.rb#3
module Phlex::Rails::Helpers::WithOutputBuffer
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#9
  def with_output_buffer(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails/helpers/word_wrap.rb#3
module Phlex::Rails::Helpers::WordWrap
  extend ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/helper_macros.rb#26
  def word_wrap(*args, **kwargs, &block); end
end

# source://phlex-rails//lib/phlex/rails.rb#7
class Phlex::Rails::HelpersCalledBeforeRenderError < ::StandardError; end

# source://phlex-rails//lib/phlex/rails/label_builder.rb#3
class Phlex::Rails::LabelBuilder < ::Phlex::Rails::Decorator
  # source://phlex-rails//lib/phlex/rails/label_builder.rb#4
  def object(*_arg0, **_arg1, &_arg2); end

  # source://phlex-rails//lib/phlex/rails/label_builder.rb#5
  def translation(*_arg0, **_arg1, &_arg2); end
end

# source://phlex-rails//lib/phlex/rails/layout.rb#4
module Phlex::Rails::Layout
  include ::Phlex::Rails::Helpers::CSPMetaTag
  include ::Phlex::Rails::Helpers::CSRFMetaTags
  include ::Phlex::Rails::Helpers::FaviconLinkTag
  include ::Phlex::Rails::Helpers::PreloadLinkTag
  include ::Phlex::Rails::Helpers::StylesheetLinkTag
  include ::Phlex::Rails::Helpers::ActionCableMetaTag
  include ::Phlex::Rails::Helpers::AutoDiscoveryLinkTag
  include ::Phlex::Rails::Helpers::JavascriptIncludeTag
  include ::Phlex::Rails::Helpers::JavascriptImportmapTags
  include ::Phlex::Rails::Helpers::JavascriptImportModuleTag
  include ::Phlex::Rails::Helpers::TurboRefreshMethodTag
  include ::Phlex::Rails::Helpers::TurboRefreshScrollTag
  include ::Phlex::Rails::Helpers::TurboRefreshesWith

  # source://phlex-rails//lib/phlex/rails/layout.rb#63
  def identifier; end

  # source://phlex-rails//lib/phlex/rails/layout.rb#48
  def render(view_context = T.unsafe(nil), *args, **kwargs, &block); end

  # source://phlex-rails//lib/phlex/rails/layout.rb#67
  def virtual_path; end

  class << self
    # @private
    #
    # source://phlex-rails//lib/phlex/rails/layout.rb#39
    def included(base); end
  end
end

# source://phlex-rails//lib/phlex/rails/layout.rb#19
module Phlex::Rails::Layout::Interface
  # source://phlex-rails//lib/phlex/rails/layout.rb#24
  def identifier; end

  # source://phlex-rails//lib/phlex/rails/layout.rb#20
  def render(view_context, _locals, &_arg2); end

  # source://phlex-rails//lib/phlex/rails/layout.rb#28
  def virtual_path; end
end

# source://phlex-rails//lib/phlex/rails/partial.rb#3
class Phlex::Rails::Partial
  # @return [Partial] a new instance of Partial
  #
  # source://phlex-rails//lib/phlex/rails/partial.rb#4
  def initialize(path, *args, **kwargs, &block); end

  # source://phlex-rails//lib/phlex/rails/partial.rb#11
  def render_in(view_context, &block); end
end

# source://phlex-rails//lib/phlex/rails/radio_button_builder.rb#3
class Phlex::Rails::RadioButtonBuilder < ::Phlex::Rails::Decorator
  # source://phlex-rails//lib/phlex/rails/decorator.rb#6
  def label(*_arg0, **_arg1, &_arg2); end

  # source://phlex-rails//lib/phlex/rails/radio_button_builder.rb#6
  def object(*_arg0, **_arg1, &_arg2); end

  # source://phlex-rails//lib/phlex/rails/decorator.rb#6
  def radio_button(*_arg0, **_arg1, &_arg2); end

  # source://phlex-rails//lib/phlex/rails/radio_button_builder.rb#4
  def text(*_arg0, **_arg1, &_arg2); end

  # source://phlex-rails//lib/phlex/rails/radio_button_builder.rb#5
  def value(*_arg0, **_arg1, &_arg2); end
end

# source://phlex-rails//lib/phlex/rails/sgml.rb#3
module Phlex::Rails::SGML
  mixes_in_class_methods ::Phlex::Rails::SGML::ClassMethods
  mixes_in_class_methods ::Phlex::Rails::HelperMacros

  # If we’re rendered from view_component, we need to capture on the view_component context.
  #
  # source://phlex-rails//lib/phlex/rails/sgml.rb#80
  def capture_context; end

  # @return [Boolean]
  #
  # source://phlex-rails//lib/phlex/rails/sgml.rb#143
  def enable_cache_reloading?; end

  # source://phlex-rails//lib/phlex/rails/sgml.rb#50
  def helpers; end

  # source://phlex-rails//lib/phlex/rails/sgml.rb#107
  def low_level_cache(*_arg0, **_arg1, &_arg2); end

  # source://phlex-rails//lib/phlex/rails/sgml.rb#18
  def method_missing(name, *_arg1, **_arg2, &_arg3); end

  # source://phlex-rails//lib/phlex/rails/sgml.rb#42
  def partial(*_arg0, **_arg1, &block); end

  # source://phlex-rails//lib/phlex/rails/sgml.rb#84
  def render(renderable = T.unsafe(nil), &block); end

  # source://phlex-rails//lib/phlex/rails/sgml.rb#111
  def render_in(view_context, &erb); end

  # source://phlex-rails//lib/phlex/rails/sgml.rb#139
  def set_original_view_context(view_context); end

  # source://phlex-rails//lib/phlex/rails/sgml.rb#69
  def view_context; end

  class << self
    # @private
    #
    # source://phlex-rails//lib/phlex/rails/sgml.rb#6
    def included(base); end
  end
end

# source://phlex-rails//lib/phlex/rails/sgml.rb#12
module Phlex::Rails::SGML::ClassMethods
  # source://phlex-rails//lib/phlex/rails/sgml.rb#13
  def render_in(*_arg0, **_arg1, &_arg2); end
end

# source://phlex-rails//lib/phlex/rails/sgml/state.rb#3
module Phlex::Rails::SGML::State
  # source://phlex-rails//lib/phlex/rails/sgml/state.rb#4
  def buffer; end

  # source://phlex-rails//lib/phlex/rails/sgml/state.rb#8
  def capture; end
end

# source://phlex-rails//lib/phlex/rails/svg.rb#3
module Phlex::Rails::SVG
  include ::Phlex::Rails::SGML

  mixes_in_class_methods ::Phlex::Rails::SGML::ClassMethods
  mixes_in_class_methods ::Phlex::Rails::HelperMacros

  # source://phlex-rails//lib/phlex/rails/svg.rb#9
  def format; end

  class << self
    # @private
    #
    # source://phlex-rails//lib/phlex/rails/svg.rb#4
    def included(base); end
  end
end

# source://phlex-rails//lib/phlex/rails/streaming.rb#3
module Phlex::Rails::Streaming
  include ::ActionController::Live
  extend ::ActionController::Live::ClassMethods

  private

  # source://phlex-rails//lib/phlex/rails/streaming.rb#21
  def __phlex_set_stream_headers__(last_modified:); end

  # source://phlex-rails//lib/phlex/rails/streaming.rb#29
  def __phlex_stream_csv__(view, filename:); end

  # source://phlex-rails//lib/phlex/rails/streaming.rb#38
  def __phlex_stream_html__(view); end

  # source://phlex-rails//lib/phlex/rails/streaming.rb#8
  def stream(view, last_modified: T.unsafe(nil), filename: T.unsafe(nil)); end
end

class Phlex::SGML::State
  include ::Phlex::Rails::SGML::State
end

class Phlex::SVG < ::Phlex::SGML
  include ::Phlex::Rails::SVG
  include ::Phlex::Rails::SGML
  extend ::Phlex::Rails::SGML::ClassMethods
  extend ::Phlex::Rails::HelperMacros
end
