---
version: 1
callbacks:
- class: CadernetaController
  applies_self: CadernetaController & DeviseScopedHelpers::UserAuthenticated
  runs_before:
  - index
  - show
  applies_constants:
    Current: singleton(Current) & Current::UserPopulated
- class: DosesController
  applies_self: DosesController & DeviseScopedHelpers::UserAuthenticated
  runs_before:
  - show
  - new
  - edit
  - create
  applies_constants:
    Current: singleton(Current) & Current::UserPopulated
- class: SugestoesController
  applies_self: SugestoesController & DeviseScopedHelpers::UserAuthenticated
  runs_before:
  - index
  applies_constants:
    Current: singleton(Current) & Current::UserPopulated
- class: VacinasController
  applies_self: VacinasController & DeviseScopedHelpers::UserAuthenticated
  runs_before:
  - index
  - show
  - new
  - edit
  - create
  - update
  - destroy
  applies_constants:
    Current: singleton(Current) & Current::UserPopulated
- class: ApplicationController
  applies_self: ApplicationController & DeviseScopedHelpers::UserAuthenticated
  runs_before:
  - set_authenticated_user
- class: DosesController
  applies_self: DosesController & DeviseScopedHelpers::UserAuthenticated
  runs_before:
  - set_dose
  - set_vacina
- class: VacinasController
  applies_self: VacinasController & DeviseScopedHelpers::UserAuthenticated
  runs_before:
  - set_vacina
