# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `RentalMailer`.
# Please instead update this file by running `bin/tapioca dsl RentalMailer`.


class RentalMailer
  class << self
    sig { returns(::ActionMailer::MessageDelivery) }
    def confirmation; end
  end
end
