---
version: 1
methods:
  Column#set_default_user_name:
    requires:
    - kind: not_nil
      expr:
        kind: send
        receiver:
          kind: self
        method: board
  Users::RegistrationsController#configure_account_update_params:
    requires:
    - kind: not_nil
      expr:
        kind: send
        receiver:
          kind: self
        method: devise_parameter_sanitizer
    enforced: false
  Users::RegistrationsController#configure_sign_up_params:
    requires:
    - kind: not_nil
      expr:
        kind: send
        receiver:
          kind: self
        method: devise_parameter_sanitizer
    enforced: false
