---
version: 1
methods:
  Caderneta::RecomendacaoVacina#dose_recomendada_atual:
    requires:
    - kind: not_nil
      expr:
        kind: send
        receiver:
          kind: self
        method: vacina
        chain:
        - dose_do_calendarios
    enforced: false
