---
version: 1
methods:
  Caderneta::Atualizar#atualizar_calendario!:
    requires:
    - kind: not_nil
      expr:
        kind: send
        receiver:
          kind: self
        method: caderneta
    - kind: not_nil
      expr:
        kind: send
        receiver:
          kind: self
        method: caderneta
        chain:
        - recomendacao_vacinas
    enforced: false
  Caderneta::Atualizar#call:
    requires:
    - kind: not_nil
      expr:
        kind: send
        receiver:
          kind: self
        method: caderneta
        chain:
        - recomendacao_vacinas
    enforced: false
  Caderneta::Cadastrar#call:
    requires:
    - kind: not_nil
      expr:
        kind: send
        receiver:
          kind: self
        method: caderneta
        chain:
        - recomendacao_vacinas
    enforced: false
  Caderneta::Cadastrar#criar_calendario_de_vacinacao!:
    requires:
    - kind: not_nil
      expr:
        kind: send
        receiver:
          kind: self
        method: caderneta
    - kind: not_nil
      expr:
        kind: send
        receiver:
          kind: self
        method: caderneta
        chain:
        - recomendacao_vacinas
    enforced: false
  Users::RegistrationsController#__rbs_infer__run_configure_account_update_params:
    requires:
    - kind: not_nil
      expr:
        kind: send
        receiver:
          kind: self
        method: devise_parameter_sanitizer
    enforced: false
  Users::RegistrationsController#__rbs_infer__run_configure_sign_up_params:
    requires:
    - kind: not_nil
      expr:
        kind: send
        receiver:
          kind: self
        method: devise_parameter_sanitizer
    enforced: false
  Users::RegistrationsController#configure_account_update_params:
    requires:
    - kind: not_nil
      expr:
        kind: send
        receiver:
          kind: self
        method: devise_parameter_sanitizer
    enforced: false
  Users::RegistrationsController#configure_sign_up_params:
    requires:
    - kind: not_nil
      expr:
        kind: send
        receiver:
          kind: self
        method: devise_parameter_sanitizer
    enforced: false
