---
version: 1
postconditions:
- class: ActionController::HttpAuthentication::Token
  method: authenticate
  when_true:
    block_truthy: true
- class: Caderneta::Atualizar
  method: initialize
  effects:
    may_write:
    - "@caderneta"
- class: Caderneta_Caderneta_RecomendacaoVacina::ActiveRecord_Associations_CollectionProxy
  method: build
  unconditional:
    returns:
      establishes:
      - caderneta
- class: Caderneta_Caderneta_RecomendacaoVacina::ActiveRecord_Associations_CollectionProxy
  method: initialize
  effects:
    may_write:
    - "@owner"
- class: Caderneta_Caderneta_RecomendacaoVacina::ActiveRecord_Associations_CollectionProxy
  method: owner
  effects:
    returns_ivar: "@owner"
- class: Caderneta_Dose::ActiveRecord_Associations_CollectionProxy
  method: build
  unconditional:
    returns:
      establishes:
      - caderneta
- class: Caderneta_Dose::ActiveRecord_Associations_CollectionProxy
  method: initialize
  effects:
    may_write:
    - "@owner"
- class: Caderneta_Dose::ActiveRecord_Associations_CollectionProxy
  method: owner
  effects:
    returns_ivar: "@owner"
- class: Caderneta_FabricanteVacina::ActiveRecord_Associations_CollectionProxy
  method: initialize
  effects:
    may_write:
    - "@owner"
- class: Caderneta_FabricanteVacina::ActiveRecord_Associations_CollectionProxy
  method: owner
  effects:
    returns_ivar: "@owner"
- class: Caderneta_Vacina::ActiveRecord_Associations_CollectionProxy
  method: initialize
  effects:
    may_write:
    - "@owner"
- class: Caderneta_Vacina::ActiveRecord_Associations_CollectionProxy
  method: owner
  effects:
    returns_ivar: "@owner"
- class: Current
  method: pessoa=
  unconditional:
    establishes_consts:
      caderneta: untyped
- class: Current
  method: __rbs_infer_instance
  effects:
    may_write:
    - "@__rbs_infer_instance"
- class: Current
  method: caderneta=
  unconditional:
    establishes_consts:
      caderneta: "(::Caderneta & ::Caderneta::Validated)"
- class: Current
  method: set
  effects:
    may_write:
    - "@user"
- class: Current
  method: user
  effects:
    returns_ivar: "@user"
- class: Current
  method: user=
  unconditional:
    establishes_consts:
      user: "(::User & ::User::Validated)"
  effects:
    may_write:
    - "@user"
- class: Current
  method: with
  effects:
    may_write:
    - "@user"
- class: ERBDosesNew
  method: initialize
  effects:
    may_write:
    - "@dose"
- class: ERBPartialCadernetaDoses
  method: initialize
  effects:
    may_write:
    - "@vacina"
- class: ERBPartialDeviseSharedErrorMessages
  method: initialize
  effects:
    may_write:
    - "@resource"
- class: ERBPartialDosesForm
  method: initialize
  effects:
    may_write:
    - "@dose"
    - "@vacina"
- class: ERBPartialPessoasForm
  method: initialize
  effects:
    may_write:
    - "@pessoa"
- class: ERBPartialSugestoesRecomendacaoVacina
  method: initialize
  effects:
    may_write:
    - "@recomendacao_vacina"
- class: ERBPartialVacinasForm
  method: initialize
  effects:
    may_write:
    - "@vacina"
- class: ERBVacinasEdit
  method: initialize
  effects:
    may_write:
    - "@vacina"
- class: ERBVacinasNew
  method: initialize
  effects:
    may_write:
    - "@vacina"
- class: ERBVacinasShow
  method: initialize
  effects:
    may_write:
    - "@vacina"
- class: FabricanteVacina_Dose::ActiveRecord_Associations_CollectionProxy
  method: build
  unconditional:
    returns:
      establishes:
      - fabricante_vacina
- class: FabricanteVacina_Dose::ActiveRecord_Associations_CollectionProxy
  method: initialize
  effects:
    may_write:
    - "@owner"
- class: FabricanteVacina_Dose::ActiveRecord_Associations_CollectionProxy
  method: owner
  effects:
    returns_ivar: "@owner"
- class: User_Pessoa::ActiveRecord_Associations_CollectionProxy
  method: build
  unconditional:
    returns:
      establishes:
      - user
- class: User_Pessoa::ActiveRecord_Associations_CollectionProxy
  method: initialize
  effects:
    may_write:
    - "@owner"
- class: User_Pessoa::ActiveRecord_Associations_CollectionProxy
  method: owner
  effects:
    returns_ivar: "@owner"
- class: Vacina_Caderneta_RecomendacaoVacina::ActiveRecord_Associations_CollectionProxy
  method: build
  unconditional:
    returns:
      establishes:
      - vacina
- class: Vacina_Caderneta_RecomendacaoVacina::ActiveRecord_Associations_CollectionProxy
  method: initialize
  effects:
    may_write:
    - "@owner"
- class: Vacina_Caderneta_RecomendacaoVacina::ActiveRecord_Associations_CollectionProxy
  method: owner
  effects:
    returns_ivar: "@owner"
- class: Vacina_Dose::ActiveRecord_Associations_CollectionProxy
  method: initialize
  effects:
    may_write:
    - "@owner"
- class: Vacina_Dose::ActiveRecord_Associations_CollectionProxy
  method: owner
  effects:
    returns_ivar: "@owner"
- class: Vacina_DoseDoCalendario::ActiveRecord_Associations_CollectionProxy
  method: build
  unconditional:
    returns:
      establishes:
      - vacina
- class: Vacina_DoseDoCalendario::ActiveRecord_Associations_CollectionProxy
  method: initialize
  effects:
    may_write:
    - "@owner"
- class: Vacina_DoseDoCalendario::ActiveRecord_Associations_CollectionProxy
  method: owner
  effects:
    returns_ivar: "@owner"
- class: Vacina_FabricanteVacina::ActiveRecord_Associations_CollectionProxy
  method: build
  unconditional:
    returns:
      establishes:
      - vacina
- class: Vacina_FabricanteVacina::ActiveRecord_Associations_CollectionProxy
  method: initialize
  effects:
    may_write:
    - "@owner"
- class: Vacina_FabricanteVacina::ActiveRecord_Associations_CollectionProxy
  method: owner
  effects:
    returns_ivar: "@owner"
