# resolve-type-names: false

class ::Caderneta < ::ApplicationRecord
  class ::Caderneta::RecomendacaoVacina < ::ApplicationRecord
    extend ::ActiveRecord::Base::ClassMethods[::Caderneta::RecomendacaoVacina, ::Caderneta::RecomendacaoVacina::ActiveRecord_Relation, ::Integer]

    module ::Caderneta::RecomendacaoVacina::GeneratedAttributeMethods
      def id: () -> ::Integer

      def id=: (::Integer) -> ::Integer

      def id?: () -> bool

      def id_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def id_change: () -> [ ::Integer?, ::Integer? ]

      def id_will_change!: () -> void

      def id_was: () -> ::Integer?

      def id_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def id_previous_change: () -> ::Array[::Integer?]?

      def id_previously_was: () -> ::Integer?

      def id_before_last_save: () -> ::Integer?

      def id_change_to_be_saved: () -> ::Array[::Integer?]?

      def id_in_database: () -> ::Integer?

      def saved_change_to_id: () -> ::Array[::Integer?]?

      def saved_change_to_id?: () -> bool

      def will_save_change_to_id?: () -> bool

      def restore_id!: () -> void

      def clear_id_change: () -> void

      def id_before_type_cast: () -> ::Integer

      def id_for_database: () -> ::Integer

      def vacina_id: () -> ::Integer?

      def vacina_id=: (::Integer?) -> ::Integer?

      def vacina_id?: () -> bool

      def vacina_id_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def vacina_id_change: () -> [ ::Integer?, ::Integer? ]

      def vacina_id_will_change!: () -> void

      def vacina_id_was: () -> ::Integer?

      def vacina_id_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def vacina_id_previous_change: () -> ::Array[::Integer?]?

      def vacina_id_previously_was: () -> ::Integer?

      def vacina_id_before_last_save: () -> ::Integer?

      def vacina_id_change_to_be_saved: () -> ::Array[::Integer?]?

      def vacina_id_in_database: () -> ::Integer?

      def saved_change_to_vacina_id: () -> ::Array[::Integer?]?

      def saved_change_to_vacina_id?: () -> bool

      def will_save_change_to_vacina_id?: () -> bool

      def restore_vacina_id!: () -> void

      def clear_vacina_id_change: () -> void

      def vacina_id_before_type_cast: () -> ::Integer?

      def vacina_id_for_database: () -> ::Integer?

      def created_at: () -> ::ActiveSupport::TimeWithZone

      def created_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

      def created_at?: () -> bool

      def created_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def created_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

      def created_at_will_change!: () -> void

      def created_at_was: () -> ::ActiveSupport::TimeWithZone?

      def created_at_previously_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def created_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def created_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

      def created_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

      def created_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def created_at_in_database: () -> ::ActiveSupport::TimeWithZone?

      def saved_change_to_created_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def saved_change_to_created_at?: () -> bool

      def will_save_change_to_created_at?: () -> bool

      def restore_created_at!: () -> void

      def clear_created_at_change: () -> void

      def created_at_before_type_cast: () -> ::Time

      def created_at_for_database: () -> ::Time

      def updated_at: () -> ::ActiveSupport::TimeWithZone

      def updated_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

      def updated_at?: () -> bool

      def updated_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def updated_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

      def updated_at_will_change!: () -> void

      def updated_at_was: () -> ::ActiveSupport::TimeWithZone?

      def updated_at_previously_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def updated_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def updated_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

      def updated_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

      def updated_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def updated_at_in_database: () -> ::ActiveSupport::TimeWithZone?

      def saved_change_to_updated_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def saved_change_to_updated_at?: () -> bool

      def will_save_change_to_updated_at?: () -> bool

      def restore_updated_at!: () -> void

      def clear_updated_at_change: () -> void

      def updated_at_before_type_cast: () -> ::Time

      def updated_at_for_database: () -> ::Time

      def status_vacinal: () -> ::String?

      def status_vacinal=: (::String?) -> ::String?

      def status_vacinal?: () -> bool

      def status_vacinal_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def status_vacinal_change: () -> [ ::String?, ::String? ]

      def status_vacinal_will_change!: () -> void

      def status_vacinal_was: () -> ::String?

      def status_vacinal_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def status_vacinal_previous_change: () -> ::Array[::String?]?

      def status_vacinal_previously_was: () -> ::String?

      def status_vacinal_before_last_save: () -> ::String?

      def status_vacinal_change_to_be_saved: () -> ::Array[::String?]?

      def status_vacinal_in_database: () -> ::String?

      def saved_change_to_status_vacinal: () -> ::Array[::String?]?

      def saved_change_to_status_vacinal?: () -> bool

      def will_save_change_to_status_vacinal?: () -> bool

      def restore_status_vacinal!: () -> void

      def clear_status_vacinal_change: () -> void

      def status_vacinal_before_type_cast: () -> ::Integer?

      def status_vacinal_for_database: () -> ::Integer?

      def caderneta_id: () -> ::Integer

      def caderneta_id=: (::Integer) -> ::Integer

      def caderneta_id?: () -> bool

      def caderneta_id_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def caderneta_id_change: () -> [ ::Integer?, ::Integer? ]

      def caderneta_id_will_change!: () -> void

      def caderneta_id_was: () -> ::Integer?

      def caderneta_id_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def caderneta_id_previous_change: () -> ::Array[::Integer?]?

      def caderneta_id_previously_was: () -> ::Integer?

      def caderneta_id_before_last_save: () -> ::Integer?

      def caderneta_id_change_to_be_saved: () -> ::Array[::Integer?]?

      def caderneta_id_in_database: () -> ::Integer?

      def saved_change_to_caderneta_id: () -> ::Array[::Integer?]?

      def saved_change_to_caderneta_id?: () -> bool

      def will_save_change_to_caderneta_id?: () -> bool

      def restore_caderneta_id!: () -> void

      def clear_caderneta_id_change: () -> void

      def caderneta_id_before_type_cast: () -> ::Integer

      def caderneta_id_for_database: () -> ::Integer
    end
    include ::Caderneta::RecomendacaoVacina::GeneratedAttributeMethods
    module ::Caderneta::RecomendacaoVacina::GeneratedAliasAttributeMethods
      include ::Caderneta::RecomendacaoVacina::GeneratedAttributeMethods

      alias id_value id

      alias id_value= id=

      alias id_value? id?

      alias id_value_changed? id_changed?

      alias id_value_change id_change

      alias id_value_will_change! id_will_change!

      alias id_value_was id_was

      alias id_value_previously_changed? id_previously_changed?

      alias id_value_previous_change id_previous_change

      alias id_value_previously_was id_previously_was

      alias id_value_before_last_save id_before_last_save

      alias id_value_change_to_be_saved id_change_to_be_saved

      alias id_value_in_database id_in_database

      alias saved_change_to_id_value saved_change_to_id

      alias saved_change_to_id_value? saved_change_to_id?

      alias will_save_change_to_id_value? will_save_change_to_id?

      alias restore_id_value! restore_id!

      alias clear_id_value_change clear_id_change

      alias id_value_before_type_cast id_before_type_cast

      alias id_value_for_database id_for_database
    end
    include ::Caderneta::RecomendacaoVacina::GeneratedAliasAttributeMethods

    def user: () -> ::User?
    def user=: (::User?) -> ::User?
    def build_user: (?untyped) -> ::User
    def create_user: (?untyped) -> ::User
    def create_user!: (?untyped) -> ::User
    def reload_user: () -> ::User?
    def caderneta: () -> ::Caderneta
    def caderneta=: (::Caderneta?) -> ::Caderneta?
    def reload_caderneta: () -> ::Caderneta?
    def build_caderneta: (untyped) -> ::Caderneta
    def create_caderneta: (untyped) -> ::Caderneta
    def create_caderneta!: (untyped) -> ::Caderneta
    def vacina: () -> ::Vacina
    def vacina=: (::Vacina?) -> ::Vacina?
    def reload_vacina: () -> ::Vacina?
    def build_vacina: (untyped) -> ::Vacina
    def create_vacina: (untyped) -> ::Vacina
    def create_vacina!: (untyped) -> ::Vacina
    module ::Caderneta::RecomendacaoVacina::GeneratedAssociationMethods
    end
    include ::Caderneta::RecomendacaoVacina::GeneratedAssociationMethods

    def aguardando!: () -> bool
    def aguardando?: () -> bool
    def disponivel!: () -> bool
    def disponivel?: () -> bool
    def completo!: () -> bool
    def completo?: () -> bool
    def self.status_vacinals: () -> ::ActiveSupport::HashWithIndifferentAccess[::String, ::Integer]
    def self.aguardando: () -> ::Caderneta::RecomendacaoVacina::ActiveRecord_Relation
    def self.not_aguardando: () -> ::Caderneta::RecomendacaoVacina::ActiveRecord_Relation
    def self.disponivel: () -> ::Caderneta::RecomendacaoVacina::ActiveRecord_Relation
    def self.not_disponivel: () -> ::Caderneta::RecomendacaoVacina::ActiveRecord_Relation
    def self.completo: () -> ::Caderneta::RecomendacaoVacina::ActiveRecord_Relation
    def self.not_completo: () -> ::Caderneta::RecomendacaoVacina::ActiveRecord_Relation

    module ::Caderneta::RecomendacaoVacina::GeneratedRelationMethods
      def status_vacinals: () -> ::ActiveSupport::HashWithIndifferentAccess[::String, ::Integer]

      def aguardando: () -> ::Caderneta::RecomendacaoVacina::ActiveRecord_Relation

      def not_aguardando: () -> ::Caderneta::RecomendacaoVacina::ActiveRecord_Relation

      def disponivel: () -> ::Caderneta::RecomendacaoVacina::ActiveRecord_Relation

      def not_disponivel: () -> ::Caderneta::RecomendacaoVacina::ActiveRecord_Relation

      def completo: () -> ::Caderneta::RecomendacaoVacina::ActiveRecord_Relation

      def not_completo: () -> ::Caderneta::RecomendacaoVacina::ActiveRecord_Relation
    end

    class ::Caderneta::RecomendacaoVacina::ActiveRecord_Relation < ::ActiveRecord::Relation
      include ::Enumerable[::Caderneta::RecomendacaoVacina]
      include ::Caderneta::RecomendacaoVacina::GeneratedRelationMethods
      include ::ActiveRecord::Relation::Methods[::Caderneta::RecomendacaoVacina, ::Integer]
    end

    class ::Caderneta::RecomendacaoVacina::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
      include ::Enumerable[::Caderneta::RecomendacaoVacina]
      include ::Caderneta::RecomendacaoVacina::GeneratedRelationMethods
      include ::ActiveRecord::Relation::Methods[::Caderneta::RecomendacaoVacina, ::Integer]

      def build: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Caderneta::RecomendacaoVacina
               | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Caderneta::RecomendacaoVacina]
      def create: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Caderneta::RecomendacaoVacina
                | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Caderneta::RecomendacaoVacina]
      def create!: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Caderneta::RecomendacaoVacina
                 | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Caderneta::RecomendacaoVacina]
      def reload: () -> ::Array[::Caderneta::RecomendacaoVacina]

      def replace: (::Array[::Caderneta::RecomendacaoVacina]) -> void
      def delete: (*::Caderneta::RecomendacaoVacina | ::Integer) -> ::Array[::Caderneta::RecomendacaoVacina]
      def destroy: (*::Caderneta::RecomendacaoVacina | ::Integer) -> ::Array[::Caderneta::RecomendacaoVacina]
      def <<: (*::Caderneta::RecomendacaoVacina | ::Array[::Caderneta::RecomendacaoVacina]) -> self
      def prepend: (*::Caderneta::RecomendacaoVacina | ::Array[::Caderneta::RecomendacaoVacina]) -> self
    end
  end
end

class ::Caderneta < ::ApplicationRecord
end
class ::ApplicationRecord < ::ActiveRecord::Base
end
class ::User < ::ApplicationRecord
end
class ::Vacina < ::ApplicationRecord
end
